version: '3'
services:
  web:
      image: nginx:alpine
      ports:
          - "8080:80"
      volumes:
          - ./:/var/www/
          - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      depends_on:
          - php
  php:
      build: ./docker/php
      working_dir: /var/www
      depends_on:
          - db
      volumes:
          - ./:/var/www/
      ports:
          - "9000:9000"
  db:
      image: mysql:5.7
      ports:
          - "3306:3306"
      volumes:
          - ./data:/var/lib/mysql
      environment: 
          MYSQL_ROOT_PASSWORD: password
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      depends_on:
          - db
      ports:
          - "8082:80"
      environment:
          PMA_HOST: db
